### ISSUE TITLE
[MowziesMobs-Port] blessing_sun - lagged TPS and server (client)

### ISSUE THREAD

**Issue by kitovoi111** [min2222/Cataclysm-Tweaks#3]
When I use san strike or a mob (boss) uses it, the server freezes and the client does the same.

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/Cataclysm-Tweaks/assets/147491823/3ef01aac-2ac8-4aca-9b7f-8a43435c73ad)

**Comment by kitovoi111** [comment]
Need click right click on a block and serveer lagged

**Comment by min2222** [comment]
don't post issue of unreleased mod

**Comment by deadbydaylight44** [comment]
> Owner

Okay, sorry, I won't do it again. And please update Alex's Caves, without your port it's bad ((( Why did you close it? If you have problems with Alex, I can talk to him

**Comment by kitovoi111** [comment]
Bro .. please.. return job Alex's Caves BackPort... my love mod.
